# Generated by Django 5.0.6 on 2025-05-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_membershipplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('offer', models.IntegerField()),
            ],
        ),
    ]
